tools:
    js_hint:
        enabled: true
        filter:
            paths: [public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*, public/*/*.min.js]

    php_mess_detector:
        enabled: true
        filter:
            paths: [include/*, public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*, include/Deadline/DeadlineStreamWrapper.php]

    php_cs_fixer:
        enabled: true
        filter:
            paths: [include/*, public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*]

    php_analyzer:
        enabled: true
        filter:
            paths: [include/*, public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*]

    php_code_sniffer:
        enabled: true
        filter:
            paths: [include/*, public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*, include/Deadline/DeadlineStreamWrapper.php]

    php_cpd:
        enabled: true
        excluded_dirs: [vendor, build, cache, tests]
        filter:
            paths: [include/*, public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*]

    php_code_coverage:
        enabled: false
        filter:
            paths: [include/*, public/*]
            excluded_paths: [vendor/*, build/*, cache/*, node_modules/*, tests/*]
