<?php
namespace Deadline\Translation;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 23:03:19.
 */
class KeyValueTranslationServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var KeyValueTranslationService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KeyValueTranslationService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Deadline\Translation\KeyValueTranslationService::setTemplate
     * @todo   Implement testSetTemplate().
     */
    public function testSetTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Deadline\Translation\KeyValueTranslationService::setLanguage
     * @todo   Implement testSetLanguage().
     */
    public function testSetLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Deadline\Translation\KeyValueTranslationService::setDomain
     * @todo   Implement testSetDomain().
     */
    public function testSetDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Deadline\Translation\KeyValueTranslationService::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
