<?php
namespace Deadline\Router;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 23:03:18.
 */
class RestRouterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RestRouter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RestRouter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Deadline\Router\RestRouter::addHttpVerbs
     * @todo   Implement testAddHttpVerbs().
     */
    public function testAddHttpVerbs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Deadline\Router\RestRouter::route
     * @todo   Implement testRoute().
     */
    public function testRoute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Deadline\Router\RestRouter::loadRoutes
     * @todo   Implement testLoadRoutes().
     */
    public function testLoadRoutes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
